[package]
name = "tachyon"
version = "0.1.0"
authors = ["Ralakus <12schneide@gmail.com>"]
edition = "2018"

respository = "https://github.com/Ralakus/tachyon"
homepage = "https://github.com/Ralakus/tachyon"
description = "Tachyon is a fast programming language that is minimal and simplistic with a simple and easy to read compiler"
license-file = "LICENSE"
readme = "README.md"
exclude = [
    ".vscode/**"
]

[dependencies]
tachyon_ast      = { path = "tachyon_ast",      version = "*" }
tachyon_frontend = { path = "tachyon_frontend", version = "*" }
tachyon_backend  = { path = "tachyon_backend",  version = "*" }

memmap = "*"